import Link from "next/link";
import { Trophy } from "lucide-react";
import { players as playerRecords, teams as teamRecords } from "@/lib/content";
import {
  AdminActions, AdminTable, AppShell, BroadcastView, Countdown, Hero, Leaderboard,
  LegalDisclaimer, MatchCard, PageHeader, PlayerCard, PlayerStats, QualificationProgress,
  ScoreTable, Search, SectionTitle, StandingsTable, StatCard,
  StatusBadge, SupporterCard, TeamCard, TeamRoster, TournamentCard,
  TournamentTimeline
} from "./alcl";
import { AuthForm } from "@/components/auth-form";
import { LiveApiAdmin } from "@/components/liveapi-admin";
const teams = teamRecords.map((team) => team.name);
const players = playerRecords.map((player) => player.displayName);
const tourneys=["Open Circuit #5","Midseason Invitational","Rising Stars Cup"];

export function HomePage(){
 return <AppShell><Hero/>
 <section className="section"><div className="container"><div className="grid grid-4"><StatCard label="Current season" value="Season 05"/><StatCard label="Next event" value="Sep 12"/><StatCard label="Registration" value="Open"/><StatCard label="Entry fee" value="$0"/></div></div></section>
 <section className="section"><div className="container"><SectionTitle eyebrow="Next up" title="Enter the circuit" copy="Open competitions, transparent formats, and a configurable path to the community championship." action={<Link className="btn" href="/tournaments">View all</Link>}/><div className="grid grid-3">{tourneys.map((x,i)=><TournamentCard name={x} index={i} key={x}/>)}</div></div></section>
 <section className="section" style={{background:"#0b0e13"}}><div className="container"><SectionTitle eyebrow="Season leaderboard" title="Teams setting the pace" action={<Link className="btn" href="/standings">Full standings</Link>}/><StandingsTable limit={8}/></div></section>
 <section className="section"><div className="container"><SectionTitle eyebrow="Community spotlight" title="Featured teams & players"/><div className="grid grid-3">{teams.slice(0,3).map((x,i)=><TeamCard name={x} index={i} key={x}/>)}</div><div className="grid grid-3" style={{marginTop:16}}>{players.slice(0,3).map((x,i)=><PlayerCard name={x} index={i} key={x}/>)}</div></div></section>
 <section className="section" style={{background:"#0b0e13"}}><div className="container"><SectionTitle eyebrow="Latest action" title="Recent results"/><div className="grid">{[0,1,2].map(i=><MatchCard index={i} key={i}/>)}</div></div></section>
 <section className="section"><div className="container"><SectionTitle eyebrow="Community powered" title="Supporters & history"/><div className="grid grid-3">{["Local LAN Cooperative","Creator Commons","Open Signal Studio"].map((x,i)=><SupporterCard name={x} index={i} key={x}/>)}</div><div className="card" style={{marginTop:16}}><Trophy color="var(--lime)"/><h3>ALCL Hall of Fame</h3><p>Season champions, community event winners, MVPs, and record holders.</p><Link className="btn" href="/hall-of-fame">Explore history</Link></div></div></section>
 </AppShell>
}

const info:Record<string,[string,string,string]>={
 league:["Season 05","The ALCL League","Eight weeks. Four circuit events. One championship. Follow every chapter of the current competitive season."],
 tournaments:["Competition hub","Find your next fight","Browse open registrations, live events, and completed community tournaments."],
 standings:["Season standings","Every point matters","Live cumulative standings across the ALCL Season 05 circuit."],
 teams:["Team directory","Built to compete","Discover the squads defining this season and follow their path through the circuit."],
 players:["Player directory","Meet the competitors","Profiles, performance snapshots, and team affiliations for ALCL competitors."],
 championship:["The final stage","ALCL Championship","The season’s best teams converge for one decisive weekend."],
 supporters:["Community powered","ALCL supporters","The people and groups helping independent competition thrive."],
 rules:["Competition guide","Rules & format","Clear standards for fair, consistent, and community-first competition."],
 "hall-of-fame":["ALCL history","Hall of fame","Celebrating champions, record breakers, and unforgettable seasons."],
 legal:["Policies","Legal & integrity","How ALCL operates, protects competitors, and communicates its independent status."],
 dashboard:["Competitor portal","Your dashboard","Your season at a glance—registrations, matches, and account actions."],
};

function StandardHeader({type}:{type:string}){const d=info[type]??["ALCL","Competition center","Everything you need for the current ALCL season."];return <PageHeader eyebrow={d[0]} title={d[1]} copy={d[2]}/>}

export function RoutePage({segments}:{segments:string[]}){
 const [root,id,leaf]=segments; const key=segments.join("/");
 if(root==="broadcast") return <BroadcastView type={id??"leaderboard"}/>;
 if(root==="login") return <AuthPage/>;
 if(root==="admin") return <AdminPage section={id}/>;
 if(root==="tournaments"&&id) return <TournamentDetail id={id} leaf={leaf}/>;
 if(root==="league"&&id) return <SeasonDetail season={id}/>;
 if(root==="teams"&&id) return <TeamDetail id={id}/>;
 if(root==="players"&&id) return <PlayerDetail id={id}/>;
 if(root==="dashboard") return <Dashboard type={id}/>;
 return <Directory type={root||key}/>;
}

function Directory({type}:{type:string}){
 let content:React.ReactNode;
 if(type==="tournaments") content=<div className="grid grid-3">{tourneys.concat(["Last Chance Qualifier","Community Night","ALCL Championship"]).map((x,i)=><TournamentCard name={x} index={i} key={x}/>)}</div>;
 else if(type==="teams") content=<><div className="toolbar"><Search placeholder="Search teams, players, or tournaments…"/><Link className="btn btn-primary" href="/dashboard/team/create">Create a team</Link></div><div className="grid grid-3">{teams.map((x,i)=><TeamCard name={x} index={i} key={x}/>)}</div></>;
 else if(type==="players") content=<><div className="toolbar"><Search placeholder="Search players or teams…"/></div><div className="grid grid-3">{players.map((x,i)=><PlayerCard name={x} index={i} key={x}/>)}</div></>;
 else if(type==="standings") content=<><div className="grid grid-3" style={{marginBottom:16}}><StatCard label="Events completed" value="3 / 5"/><StatCard label="Teams ranked" value="20"/><StatCard label="Qualification line" value="Top 12"/></div><StandingsTable/></>;
 else if(type==="league") content=<><div className="card" style={{marginBottom:22}}><StatusBadge status="Season active"/><h3>Open Circuit #5 begins soon</h3><Countdown/><QualificationProgress/></div><TournamentTimeline/><div style={{marginTop:40}}><StandingsTable/></div></>;
 else if(type==="championship") content=<><div className="grid grid-3"><StatCard label="Qualified teams" value="12"/><StatCard label="Scheduled matches" value="8"/><StatCard label="Awards" value="Recognition"/></div><div style={{marginTop:20}}><QualificationProgress value={66}/></div><div style={{marginTop:40}}><SectionTitle eyebrow="Qualified" title="The community field so far"/><div className="grid grid-3">{teams.slice(0,6).map((x,i)=><TeamCard name={x} index={i} key={x}/>)}</div></div><div style={{marginTop:40}}><Article sections={[["Qualification rules","Top teams qualify under the season configuration published before play."],["Format & schedule","The culminating community event uses its own published match and scoring configuration."],["Champion & history","Community recognition, badges, and season history are recorded without commercial-prize claims."]]}/></div></>;
 else if(type==="supporters") content=<div className="grid grid-3">{["Obsidian Tier","Lumen Collective","Dropzone Community"].map((x,i)=><SupporterCard name={x} index={i} key={x}/>)}</div>;
 else if(type==="hall-of-fame") content=<div className="grid grid-3">{["Season 04 · Northstar","Season 03 · Wildcards","Season 02 · Final Form"].map((x,i)=><div className="card" key={x}><Trophy color="var(--lime)"/><h3>{x}</h3><p>{12-i*2} match wins · {186-i*13} eliminations</p></div>)}</div>;
 else if(type==="rules") content=<><div className="card" style={{borderColor:"#ff6b3566",marginBottom:20}}><StatusBadge status="RULES — PLACEHOLDER"/><h3>ALCL SIGN UP RULES</h3><p>Official ALCL rules will be reviewed and published before registration opens for each event. This page is not an active ruleset and cannot be accepted for competition entry.</p></div><Article sections={["Eligibility","Team Requirements","Roster Requirements","Rank Requirements","Registration","Roster Lock","Substitutes","Match Participation","Tournament Scoring","Season Points","Championship Qualification","Conduct","Disputes","Penalties"].map((title,index)=>[`${String(index+1).padStart(2,"0")} · ${title}`,`PLACEHOLDER — Event-specific ${title.toLowerCase()} requirements will be published and versioned before the applicable community event.`] as [string,string])}/></>;
 else if(type==="legal") content=<Article sections={[["Independent Community Tournament","ALCL is an independent community tournament organization. It is not an EA, Respawn, ALGS, or other EA-entity program."],["EA Disclaimer","This tournament is not affiliated with or sponsored by Electronic Arts Inc."],["Intellectual Property","ALCL uses original branding. Organizers and participants must have rights to uploaded names, logos, images, and other materials."],["Participant Responsibilities","Participants remain responsible for applicable EA terms, platform rules, published event rules, local law, and account standing."],["Rules of Conduct","Cheating, collusion, exploits, harassment, discriminatory conduct, and falsified information are prohibited."],["Privacy","ALCL collects only tournament-operational information. Retention details and organizer contact information require reviewed language before launch."],["Terms of Participation","Participation is subject to published event-specific eligibility, roster, scoring, dispute, and conduct rules."],["Contact","PLACEHOLDER — Add the organizer’s reviewed legal, privacy, and tournament-integrity contact details before launch."]]}/>;
 else content=<StandingsTable/>;
 return <AppShell><StandardHeader type={type}/><section className="container">{content}</section></AppShell>;
}

function Article({sections}:{sections:[string,string][]}){return <div className="grid grid-2">{sections.map(([h,p])=><article className="card" key={h}><h3>{h}</h3><p>{p}</p></article>)}</div>}

function TournamentDetail({id,leaf}:{id:string;leaf?:string}){
 const title=tourneys[Number(id)-1]??id.split("-").map(part=>part[0]?.toUpperCase()+part.slice(1)).join(" ");
 let content:React.ReactNode;
 if(leaf==="leaderboard") content=<><SectionTitle eyebrow="Live table" title="Tournament leaderboard"/><Leaderboard/></>;
 else if(leaf==="matches") content=<><SectionTitle eyebrow="Schedule" title="Matches & results"/><div className="grid">{[0,1,2].map(i=><MatchCard index={i} key={i}/>)}</div></>;
 else if(leaf==="rules") content=<Article sections={[["Published event rules","Event-specific eligibility, roster, scoring, dispute, and conduct rules are versioned before registration opens."],["Tournament Scoring","Placement, kills, bonuses, penalties, multipliers, match limits, and tiebreakers use the tournament’s immutable configuration snapshot."],["Fair play","EA’s applicable terms and ALCL conduct requirements apply to every participant."]]}/>;
 else if(leaf==="teams") content=<div className="grid grid-3">{teams.slice(0,20).map((team,index)=><TeamCard name={team} index={index} key={team}/>)}</div>;
 else if(leaf==="results") content=<><SectionTitle eyebrow="Audited source results" title="Event results"/><ScoreTable/></>;
 else if(leaf==="announcements") content=<Article sections={[["Registration open","Team managers can submit an eligible five-player registered roster."],["Roster lock reminder","Changes after the published deadline require organizer approval."],["Results policy","Raw organizer-entered results are retained with scoring and audit history."]]}/>;
 else if(leaf==="schedule") content=<><SectionTitle eyebrow="Event schedule" title="Community event timeline"/><TournamentTimeline/></>;
 else if(leaf==="registration") content=<div className="card"><StatusBadge/><h3>Team roster</h3><p>Sign in as a player, then create a team and add registered player accounts to your roster. Teams do not log in.</p><Link className="btn btn-primary" href="/dashboard/team/create">Create a team</Link></div>;
 else content=<><div className="actions" style={{marginBottom:20}}>{["schedule","rules","registration","teams","leaderboard","matches","results","announcements"].map(section=><Link className="btn" href={`/tournaments/${id}/${section}`} key={section}>{section}</Link>)}</div><div className="grid grid-3"><StatCard label="Registered" value="17 / 20"/><StatCard label="Format" value="6 matches"/><StatCard label="Entry fee" value="$0"/></div><div className="grid grid-2" style={{marginTop:18}}><div className="card"><StatusBadge/><h3>Registration closes soon</h3><Countdown/><div className="actions"><Link className="btn btn-primary" href="/dashboard/team/create">Create a team</Link><Link className="btn" href={`/tournaments/${id}/matches`}>View matches</Link></div></div><QualificationProgress value={80}/></div><div style={{marginTop:50}}><SectionTitle eyebrow="Format" title="Tournament journey"/><TournamentTimeline/></div><div style={{marginTop:50}}><SectionTitle eyebrow="Results" title="Latest scores"/><ScoreTable/></div></>;
 return <AppShell><PageHeader eyebrow="ALCL community tournament" title={leaf?`${title} · ${leaf}`:title} copy="Independent community competition with configurable Tournament Scoring and Season Qualification."/><section className="container"><div className="card" style={{marginBottom:20,borderColor:"#c7ff4740"}}><LegalDisclaimer/></div>{content}</section></AppShell>
}

function SeasonDetail({season}:{season:string}){return <AppShell><PageHeader eyebrow="Season archive" title={`ALCL ${season.replace("-"," ")}`} copy="Season schedule, milestones, and cumulative performance."/><section className="container"><div className="grid grid-3"><StatCard label="Circuit events" value="5"/><StatCard label="Total teams" value="20"/><StatCard label="Current week" value="06"/></div><div style={{marginTop:50}}><TournamentTimeline/></div><div style={{marginTop:50}}><StandingsTable/></div></section></AppShell>}
function TeamDetail({id}:{id:string}){const i=Math.max(0,(Number(id)||1)-1);const name=teams[i%teams.length];return <AppShell><PageHeader eyebrow={`#${i+1} · Community team`} title={name} copy="A fictional development team profile with original ALCL branding."/><section className="container"><div className="grid grid-4"><StatCard label="Season points" value={String(Math.max(20,126-i*5))}/><StatCard label="Event wins" value={String(Math.max(0,4-Math.floor(i/4)))}/><StatCard label="Kills" value={String(128-i*4)}/><StatCard label="Region" value={i%3===0?"Europe":"North America"}/></div><div className="grid grid-2" style={{marginTop:18}}><div className="card"><h3>Team profile</h3><p>Abbreviation: {name.slice(0,3).toUpperCase()} · Manager: Demo Manager {i+1}</p><p>Website and creator/social links are organizer-moderated before publication.</p><div className="actions"><button className="btn">Website</button><button className="btn">Creator links</button></div></div><div className="card"><h3>Achievements</h3><p>Community finalist · Match winner · Season Qualification contender</p><Link className="btn" href="/standings">Event history</Link></div></div><div style={{marginTop:45}}><SectionTitle eyebrow="Registered roster" title="3 starters · up to 2 substitutes"/><TeamRoster/></div><div style={{marginTop:40}}><SectionTitle eyebrow="Event history" title="Season performance"/><StandingsTable limit={5}/></div></section></AppShell>}
function PlayerDetail({id}:{id:string}){const i=Math.max(0,(Number(id)||1)-1);const name=players[i%players.length];return <AppShell><PageHeader eyebrow={`${teams[i%teams.length]} · ${["IGL","Fragger","Support","Flex","Substitute"][i%5]}`} title={name} copy="Fictional player profile and organizer-entered ALCL competition performance."/><section className="container"><PlayerStats index={i}/><div className="grid grid-2" style={{marginTop:18}}><div className="card"><h3>Player details</h3><p>Region: {i%3===0?"Europe":"North America"} · Current rank: {i%19===0?"Predator":"Diamond"}</p><p>Rank history is self-reported or organizer-verified and never collected through EA credentials or private APIs.</p></div><div className="card"><h3>Achievements & links</h3><p>Community match winner · Top-five finisher · Social links pending moderation</p></div></div><div style={{marginTop:40}}><SectionTitle eyebrow="Event history" title="Recent performance"/><ScoreTable/></div></section></AppShell>}

function Dashboard({type}:{type?:string}){
 const label=type==="team"?"Team workspace":type==="player"?"Player workspace":"Overview";
 return <AppShell><PageHeader eyebrow="Signed in · Demo mode" title={label} copy="Role-aware ALCL competition tools. Connected environments use Supabase Auth and row-level security."/><section className="container">
  <div className="grid grid-4"><StatCard label="Season rank" value="#04" change="↑ 2 places"/><StatCard label="Season points" value="111"/><StatCard label="Registration" value="Pending"/><StatCard label="Next event" value="Sep 12"/></div>
  <div className="grid grid-2" style={{marginTop:18}}><QualificationProgress value={72}/><div className="card"><h3>Qualification status</h3><p>Currently above the provisional top-12 qualification line.</p><Link className="btn" href="/championship">View qualification</Link></div></div>
  {type==="team"?<div className="card" style={{marginTop:18}}><h3>Team manager</h3><p>As team manager you control roster, registration, and lineups. Roster slots are separate player accounts.</p><div className="actions"><Link className="btn btn-primary" href="/dashboard/team/create">Create a team</Link><button className="btn">Set match lineup</button><button className="btn">Request roster change</button></div></div>:null}
  {type==="player"?<div className="card" style={{marginTop:18}}><h3>Player profile</h3><p>Review your role, self-reported rank snapshot, event history, wins, kills, achievements, and social links.</p><div className="actions"><button className="btn btn-primary">Edit profile</button><Link className="btn" href="/players/1">View public profile</Link></div></div>:null}
  <div className="grid grid-2" style={{marginTop:18}}><div className="card"><h3>Recent result</h3><p>Community Open · Match 6 · 23 match points</p><Link className="btn" href="/tournaments/community-open-1/results">View audited result</Link></div><div className="card"><h3>Notifications</h3><p>Registration changes requested · Roster lock approaching · Season standings updated</p><button className="btn">Mark all read</button></div></div>
 </section></AppShell>
}

function AdminPage({section}:{section?:string}){const name=section?section[0].toUpperCase()+section.slice(1):"Operations";return <AppShell><PageHeader eyebrow="Organizer console · RLS protected" title={name} copy="Dense competition administration with server-enforced policy checks and immutable audit history."/><section className="container"><div className="grid grid-4" style={{marginBottom:22}}><StatCard label="Pending review" value="08"/><StatCard label="Active events" value="03"/><StatCard label="Registered teams" value="20"/><StatCard label="Open flags" value="02"/></div><AdminActions title={name}/>
{!section&&<div className="grid grid-3" style={{marginBottom:16}}><div className="card"><h3>Season operations</h3><p>Manage seasons, announcements, community championship qualification, and published rules.</p><button className="btn">Manage season</button></div><div className="card"><h3>Standings</h3><p>Recalculate deterministic standings from raw results and versioned scoring configuration.</p><button className="btn">Recalculate</button></div><div className="card"><h3>Audit logs</h3><p>Review append-only mutations, actor identity, timestamps, and before/after records.</p><button className="btn">View audit log</button></div></div>}
{section==="registrations"&&<div className="card" style={{marginBottom:16}}><h3>Registration review</h3><p>Review team, five-player roster, rank snapshots, eligibility, and submission timestamp.</p><div className="actions"><button className="btn btn-primary">Approve</button><button className="btn">Request changes</button><button className="btn">Reject</button><button className="btn">Lock registration</button></div></div>}
{section==="matches"&&<div className="card" style={{marginBottom:16}}><h3>Manual result entry</h3><p>Enter placements, team kills, player kills, bonuses, and penalties. Calculated totals are derived and auditable.</p><div className="actions"><button className="btn btn-primary">Create match</button><button className="btn">Enter results</button><button className="btn">Verify results</button></div></div>}
{section==="live-data"&&<LiveApiAdmin/>}
{section==="supporters"&&<div className="card" style={{marginBottom:16}}><h3>Supporter moderation</h3><p>Publishing requires category, content, rights, and tournament-guideline attestations. Prohibited categories are rejected server-side.</p><div className="actions"><button className="btn btn-primary">Add supporter</button><button className="btn">Review attestations</button></div></div>}
{section==="scoring"&&<div className="card" style={{marginBottom:16}}><h3>Tournament Scoring configuration</h3><div className="grid grid-3"><label className="field">First-place points<input className="input" defaultValue="12"/></label><label className="field">Kill points<input className="input" defaultValue="1"/></label><label className="field">Maximum matches<input className="input" defaultValue="6"/></label><label className="field">Bonus configuration<input className="input" defaultValue="{}"/></label><label className="field">Penalty configuration<input className="input" defaultValue="{}"/></label><label className="field">Tiebreakers<input className="input" defaultValue="Points, wins, kills"/></label></div><div className="actions"><button className="btn btn-primary">Save versioned ruleset</button><button className="btn">Preview scoring</button></div></div>}
<AdminTable kind={(section??"operation").slice(0,-1)}/></section></AppShell>}

function AuthPage(){return <AppShell><div className="container" style={{display:"grid",placeItems:"center",minHeight:"65vh"}}><div className="card" style={{width:"min(440px,100%)"}}><div className="eyebrow">Player sign in</div><h3 style={{fontSize:30}}>Sign in as a player</h3><p className="legal">Teams do not have logins. Only players sign in.</p><AuthForm/></div></div></AppShell>}
